apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: microservice-pipeline
build:
  artifacts:
    - image: gitea.tuxgrid.com/pboyd/auth-api
      context: auth-api
      kaniko:
        dockerfile: Dockerfile
    - image: gitea.tuxgrid.com/pboyd/data-api
      context: data-api
      kaniko:
        dockerfile: Dockerfile
  cluster:
    pullSecretName: registry-credentials
    namespace: jenkins
profiles:
  - name: local
    build:
      artifacts:
        - image: gitea.tuxgrid.com/pboyd/auth-api
          context: auth-api
          kaniko:
            dockerfile: Dockerfile
        - image: gitea.tuxgrid.com/pboyd/data-api
          context: data-api
          kaniko:
            dockerfile: Dockerfile
      cluster:
        pullSecretName: registry-credentials
        namespace: default
    manifests:
      kustomize:
        paths:
          - auth-api/k8s/overlays/dev
          - data-api/k8s/overlays/dev
    portForward:
      - resourceType: service
        resourceName: auth-api
        port: 8080
        localPort: 8081
      - resourceType: service
        resourceName: data-api
        port: 8080
        localPort: 8082
  - name: dev
    manifests:
      kustomize:
        paths:
          - auth-api/k8s/overlays/dev
          - data-api/k8s/overlays/dev
  - name: test
    manifests:
      kustomize:
        paths:
          - auth-api/k8s/overlays/test
          - data-api/k8s/overlays/test
  - name: production
    manifests:
      kustomize:
        paths:
          - auth-api/k8s/overlays/production
          - data-api/k8s/overlays/production
deploy:
  kubectl: {}
